name: Rust

on: push

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install `rust` toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal # minimal component installation (ie, no documentation)
          components: rustfmt, clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install `rust` toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal # minimal component installation (ie, no documentation)
          components: rustfmt, clippy
      - name: build and run tests
        run: cargo test
