name: Rust

on: push

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install `rust` toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal # minimal component installation (ie, no documentation)
          toolchain: stable
          components: rustfmt, clippy
      - uses: giraffate/clippy-action@v1
        with:
          reporter: "github-pr-review"
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install `rust` toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal # minimal component installation (ie, no documentation)
          toolchain: stable
          components: rustfmt, clippy
      - name: build and run tests
        run: cargo test
